### ISSUE TITLE
SetFormatFunc is useless

### ISSUE THREAD

**Issue by dengshuan** [go-playground/log#6]
Though `SetFormatFunc` method is exported in every handler, users actually can do nothing with this. Since none of the handlers' struct have any exported field, users can't customize their own format function.

Either making some fields exported or adding some getters to make this method usable. What do you think about it?

**Comment by joeybloggs** [comment]
Hey @dengshuan although not useless, it may be a little easier if I passed the handler's Struct to the format function and added some getters.

I was originally thinking that one would dynamically create the function and therefore have access to any variable that would have been passed or set on the handler and not need the handler fields, but I can see how it may be more useful to expose the fields.

I will take a look at look at it this morning and see what I can't come up with.

**Comment by joeybloggs** [comment]
OK @dengshuan updated to pass handler struct for FormatFunc + exposed the necessary fields, see commit 4b4ebd1dc72b8683acaedb3fb24adf2630d45aaa

please let me know if I missed anything and thanks for you thoughts 👍

**Comment by dengshuan** [comment]
Great, thank you for your quick reply and fix. With this commit, I can now truly customize syslog format function. The default format function in syslog handler prints timestamp and log level twice, because `stdsyslog` already prints timestamp and log level (priority actually) according to [syslog standard](https://www.ietf.org/rfc/rfc3164.txt)
> The full format of a syslog message seen on the wire has three
   discernable parts.  The first part is called the PRI, the second part
   is the HEADER, and the third part is the MSG.

which the `PRI` part contains priority and `HEADER` part contains timestamp

But since there's an exported function `SetFormatFunc` for the handler, users can define their own format function. I don't know if this is a real problem

**Comment by joeybloggs** [comment]
The main reasons it was done that way is because the libraries levels don't line up 100% with syslog log levels i.e.
```go
case log.TraceLevel, log.InfoLevel:
			s.writer.Info(line)

case log.PanicLevel, log.AlertLevel:
			s.writer.Alert(line)
```

if you do not wish to lose that it was a TRACE or PANIC vs INFO or ALERT you need to print the level

and secondly not all syslog recipients handle nanosecond precision and so was also printing that out to ensure the logs could handle that precision.

I agree that not everyone may need or want that, but as you said, one only has to define their own format, so don;t think it's an issue.

Glad I could help, let me know if there's anything else 😄
